# Kubernetes ConfigMap providing environment variables for the IoT processor
apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-processor-config
  namespace: default
data:
  PROJECT_ID: "lbg-ecpdataplatform"
  SUBSCRIPTION_ID: "lbg-ecpdataplatform-dev-iot-topic-sub"
  BUCKET_NAME: "lbg-ecpdataplatform-dev-data-bucket"
  BIGQUERY_DATASET: "dev_dataset"
  BIGQUERY_TABLE: "iot_table"
